version: '3'

services:

  lity-api:
    image: ${API_IMAGE}

    container_name: ${API_CONTAINER_NAME}
    env_file:
      - ${API_ENV}
    ports:
      - ${API_EXTERNAL_PORT}:5000
    command: sh -c "java -jar deployment.jar"

    deploy:
      resources:
        limits:
          memory: 1024m